# Generated by Django 3.0.4 on 2021-08-02 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_profile', '0017_hrprofile_status_reason'),
        ('backend', '0017_auto_20210624_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_ym', models.CharField(max_length=6, verbose_name='청구년월')),
                ('demand_amount', models.IntegerField(default=0, null=True, verbose_name='청구금액')),
                ('paidup_ymdt', models.DateTimeField(auto_now_add=True, verbose_name='지불일자')),
                ('paidup_yn', models.BooleanField(default=False, verbose_name='지불여부')),
                ('discount_ratio', models.FloatField(default=0, verbose_name='할인율')),
                ('hrprofile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hr_profile.HrProfile')),
            ],
            options={
                'verbose_name_plural': '청구 / Demand',
            },
        ),
    ]
