# Generated by Django 3.0.4 on 2021-07-08 00:53

import company_profile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0035_auto_20210624_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugubsuccess',
            options={'verbose_name_plural': '2_4. 합격 채용의뢰서 / SugubSuccess'},
        ),
        migrations.AddField(
            model_name='sugubsuccess',
            name='sugub_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='수급제목'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to=company_profile.models.company_directory_path, verbose_name='회사대표이미지'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=company_profile.models.company_directory_path, verbose_name='회사로고'),
        ),
    ]
